project/config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'

  devise_for :admin_users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  get 'welcome/index'
  get 'welcome/check_login_and_redirect', as: :check_login_and_redirect
  get 'events/password', as: :page_authenticate
  post 'events/:id' => 'events#show'
  get 'mypage' => 'users#mypage', as: :mypage
  get '/auth/:provider/callback' => 'sessions#create'
  get '/login' => 'sessions#create', as: :login
  get '/logout' => 'sessions#destroy', as: :logout

  resource :user, only: :destroy do
    get 'retire'
  end

  resources :events do
    resources :tickets, only: [:new, :create, :destroy]
  end
  match '*path' => 'application#error404', via: :all

end

project/app/models/event.rb
class Event < ActiveRecord::Base
  mount_uploader :event_image, EventImageUploader

  has_many :tickets, dependent: :destroy#親のオブジェクトのレコードが削除されたら同時に削除
  belongs_to :owner, class_name: 'User'

  has_many :event_attachments, dependent: :destroy
  accepts_nested_attributes_for :event_attachments

  validates :name, length: { maximum: 50 }, presence: true
  validates :place, length: { maximum: 100 }, presence: true
  validates :content, length: { maximum: 2000 }, presence: true
  validates :start_time, presence: true
  validates :end_time, presence: true
  validate  :start_time_should_be_before_end_time

  before_save :password_to_digest

  def created_by?(user)
    return false unless user
    owner_id == user.id
  end

  def authenticate(password)
    return false if self.password.blank? || password.blank?
    Digest::MD5.new.update(password).to_s == self.password
  end

  private

  def password_to_digest
    if self.password.blank?
      self.password = nil
    else
      self.password = Digest::MD5.new.update(self.password).to_s
    end
    self
  end

  def start_time_should_be_before_end_time
    return unless start_time && end_time

    if start_time >= end_time
      errors.add(:start_time, 'は終了時間よりも前に設定してください')
    end
  end
end

project/app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate, except: [:show, :index, :password] #show以外はログインさせる
  before_action :store_location, except: [:password, :destroy]

  # 1ページに表示する件数
  PER = 10

  # 添付できるファイルの最大数
  EVENT_ATTACHMENT_LIMIT = 5

  def index
    @q = Event.where("password is ?", nil).order(:start_time).page(params[:page]).per(PER).search(search_params)
    @events = @q.result(distinct: true)
  end

  def show
    @event = Event.find(params[:id])

    unless @event.owner == current_user || @event.password.nil?
      pass = params[:password]
      path = page_authenticate_path({ url: event_path(@event) })

      return redirect_to path if pass.nil?
      return redirect_to path, alert: 'パスワードが違います！' unless @event.authenticate(pass)
    end

    @ticket  = current_user && current_user.tickets.find_by(event_id: params[:id])
    @tickets = @event.tickets.includes(:user).order(:created_at) # イベントに参加したユーザ一覧を作成時間順に表示
  end

  def new
    @event = current_user.created_events.build
    @event_attachments = @event.event_attachments.build
  end

  def create
    @event = current_user.created_events.build(event_params)
    
    if @event.save
      error_msg = create_event_attachments( params[:event_attachments_new] )

      unless error_msg.blank?
        flash.now[:alert] = error_msg
        render :new and return
      end

      redirect_to @event, notice: '作成しました'
    else
      render :new
    end
  end

  def edit
    @event = current_user.created_events.find(params[:id])
    @event_attachments = @event.event_attachments
  end

  def update
    @event = current_user.created_events.find(params[:id])

    if @event.update(event_params)
      error_msg = create_event_attachments( params[:event_attachments_new] )

      unless error_msg.blank?
        flash.now[:alert] = error_msg
        render :edit and return
      end

      unless params[:event_attachments].blank?
        params[:event_attachments]['remove_id'].each do |id|
          @event.event_attachments.find(id).destroy! unless id == '0'
        end
      end
      redirect_to @event, notice: '更新しました'
    else
      render :edit
    end
  end

  def destroy
    @event = current_user.created_events.find(params[:id])
    @event_name = @event.name
    @event.destroy!
    redirect_to root_path, notice: "「#{@event_name}」を削除しました"
  end

  def password
    @url = params[:url]
  end

  private

  def event_params
    params.require(:event).permit(
      :name, :place, :event_image, :event_image_cache, :remove_event_image, :content, :start_time, :end_time, :password,
      :event_attachments_new
    )
  end

  def create_event_attachments(event_attachments_new)
    return "" if event_attachments_new.blank?
    limit     = EVENT_ATTACHMENT_LIMIT - @event.event_attachments.count
    error_msg = ""

    event_attachments_new['url'].each do |url|
      break if --limit < 0
      @event_attachment = @event.event_attachments.build(:url => url, :event_id => @event.id)
      unless @event_attachment.save
        @event_attachment.errors.full_messages.each { |msg| error_msg += msg }
        @event_attachment.delete
      end
    end

    return error_msg
  end
end

project/app/helpers/events_helper.rb
module EventsHelper
end

project/app/views/events/edit.html.erb
<% now = Time.zone.now %>
<% provide(:page_title, "イベント編集") %>

<section class="container">
  <%= render partial: 'shared/flash_message' %>
  <div class="page-header">
    <h3>イベント情報編集</h3>
  </div>

  <%= form_for(@event, class: 'form-horizontal', role: 'form') do |f| %>
    <% if @event.errors.any? %>
      <div class="alert alert-danger">
        <ul>
          <% @event.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control', required: true, placeholder: '必須入力' %>
    </div>

    <div class="form-group">
      <%= f.label :place %>
      <%= f.text_field :place, class: 'form-control', required: true, placeholder: '必須入力' %>
    </div>

    <div class="form-group">
      <% if @event.event_image? %>
        <div class="thumbnail">
          <%= image_tag @event.event_image.url %>
        </div>
      <% end %>
      <%= f.file_field :event_image, class: 'js-img-upload' %>
      <%= f.hidden_field :event_image_cache %>
    </div>
    <% if @event.event_image? %>
      <div class="checkbox">
        <label>
          <%= f.check_box :remove_event_image %>
          画像を削除する
        </label>
      </div>
    <% end %>

    <div class="form-group form-inline">
      <%= f.label :start_time %>
      <div>
        <%= f.datetime_select :start_time, {start_year: now.year, end_year: now.year + 1, use_month_numbers: true, with_css_classes: true}, class: 'form-control' %>
      </div>
    </div>
    <div class="form-group form-inline">
      <%= f.label :end_time %>
      <div>
        <%= f.datetime_select :end_time, {start_year: now.year, end_year: now.year + 1, use_month_numbers: true, with_css_classes: true}, class: 'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :content %>
      <%= f.text_area :content, class: 'form-control', rows: 10, required: true, placeholder: '必須入力' %>
      <span class="help-block">Markdown記法が利用できます。</span>
    </div>
    <div class="form-group">
      <%= f.label :password %> (半角英数字)
      <%= f.password_field :password, class: 'form-control', placeholder: 'イベントの閲覧に必要なパスワード', pattern: '[a-zA-Z0-9]+' %>
      <span class="help-block">パスワードを設定すると、主催者以外は閲覧時にパスワードが必要になります。また、検索結果には表示されなくなります。</span>
    </div>
    
    <div class="form-group" id="filelist">
      <label>添付ファイル</label>
      <span class="help-block">5個までファイルをアップロードできます。1ファイルのサイズは5メガバイトまでです。</span>
      <% @event.event_attachments.each do |a| %>
        <% if a.url.present? %>
          <div class="checkbox">
            <label>
              <%= f.check_box :event_attachments, { name: "event_attachments[remove_id][]", class: 'filecheckbox' }, a.id %><%= fa_icon 'trash' %>
              <%= a.url.to_s.split('/').last %>
            </label>
          </div>
        <% end %>
      <% end %>

      <%= f.fields_for :event_attachments_new do |e| %>
        <div>
          <input type="file" name="event_attachments_new[url][]" class="fileinput">
        </div>
      <% end %>
    </div>

    <%= f.submit '更新', class: 'btn btn-default', data: { disable_with: '更新中' } %>
  <% end %>
</section>

project/app/views/events/index.html.erb
<% provide(:page_title, "イベント検索") %>

<section class="container">
  <%= render partial: 'shared/flash_message' %>
  <header class="page-header">
    <h3>イベント検索</h3>
    <p class="text-muted">イベントを検索して参加してみましょう</p>
  </header>

  <%= render partial: 'shared/event_search_form', locals: {q: @q, events: @events} %>

  <%= render partial: 'shared/event_search_result', locals: {events: @events} %>
</section>


project/app/views/events/new.html.erb
<% now = Time.zone.now %>
<% provide(:page_title, "イベント作成") %>

<section class="container">
  <%= render partial: 'shared/flash_message' %>
  <div class="page-header">
    <h3>イベント作成</h3>
  </div>
  
  <%= form_for(@event, class: 'form-horizontal', role: 'form') do |f| %>
    <% if @event.errors.any? %>
      <div class="alert alert-danger">
        <ul>
          <% @event.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control', required: true, placeholder: '必須入力' %>
    </div>

    <div class="form-group">
      <%= f.label :place %>
      <%= f.text_field :place, class: 'form-control', required: true, placeholder: '必須入力' %>
    </div>

    <div class="form-group">
      <% if @event.event_image? %>
        <div class="thumbnail">
          <%= image_tag @event.event_image.url %>
        </div>
      <% end %>
      <%= f.file_field :event_image, class: 'js-img-upload' %>
      <%= f.hidden_field :event_image_cache %>
    </div>
    <% if @event.event_image? %>
      <div class="checkbox">
        <label>
          <%= f.check_box :remove_event_image %>
          画像を削除する
        </label>
      </div>
    <% end %>

    <div class="form-group form-inline">
      <%= f.label :start_time %>
      <div>
        <%= f.datetime_select :start_time, {start_year: now.year, end_year: now.year + 1, use_month_numbers: true, with_css_classes: true}, class: 'form-control' %>
      </div>
    </div>
    <div class="form-group form-inline">
      <%= f.label :end_time %>
      <div>
        <%= f.datetime_select :end_time, {start_year: now.year, end_year: now.year + 1, use_month_numbers: true, with_css_classes: true}, class: 'form-control' %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :content %>
      <%= f.text_area :content, class: 'form-control', rows: 10, required: true, placeholder: '必須入力' %>
      <span class="help-block">Markdown記法が利用できます。</span>
    </div>

    <div class="form-group" id="filelist">
      <label>添付ファイル</label>
      <span class="help-block">5個までファイルをアップロードできます。1ファイルのサイズは5メガバイトまでです。</span>
      <% @event.event_attachments.each do |a| %>
        <% if a.url.present? %>
          <div class="checkbox">
            <label>
              <%= f.check_box :event_attachments, { name: "event_attachments[remove_id][]", class: 'filecheckbox' }, a.id %><%= fa_icon 'trash' %>
              <%= a.url.to_s.split('/').last %>
            </label>
          </div>
        <% end %>
      <% end %>

      <%= f.fields_for :event_attachments_new do |e| %>
        <div>
          <input type="file" name="event_attachments_new[url][]" class="fileinput">
        </div>
      <% end %>
    </div>

    <%= f.submit '作成', class: 'btn btn-default', data: { disable_with: '作成中' } %>
  <% end %>
</section>

project/app/views/events/password.html.erb
<section class="container">
  <%= render partial: 'shared/flash_message' %>
  <header class="page-header">
    <h3>イベント情報の閲覧にパスワードが必要です</h3>
  </header>

  <%= form_tag @url, class: '' do %>
    <div class="form-group">
      <%= password_field_tag :password, nil, class: 'form-control', placeholder: 'Password' %>
    </div>
    <button type="submit" class="btn btn-default">送信</button>
  <% end %>
</section>

project/app/views/events/show.html.erb
<% provide(:title, @event.name) %>

<section class="container">
  <%= render partial: 'shared/flash_message' %>
  
  <div class="page-header">
    <h3>
      <%= @event.name %>
    </h3>
  </div>
  
  <div class="row">
    <div class="col-md-8">
      <% if @event.event_image? %>
        <div class="thumbnail">
          <%= image_tag @event.event_image.url %>
        </div>
      <% end %>
  
  
      <div class="panel panel-default">
        <div class="panel-heading">
          <%= fa_icon 'user' %>&nbsp;主催者
        </div>
        <div class="panel-body">
          <% if @event.owner %>
            <%= link_to url_for_twitter(@event.owner), target: '_blank' do %>
              <%= image_tag @event.owner.image_url, class: 'owner-image' %>
              <%= "@#{@event.owner.nickname}" %>
            <% end %>
          <% else %>
            <%= fa_icon 'user-times' %>&nbsp;退会したユーザです
          <% end %>
        </div>
      </div>
  
      <div class="panel panel-default">
        <div class="panel-heading">
          <%= fa_icon 'clock-o' %>&nbsp;開催時間
        </div>
        <div class="panel-body">
          <%= @event.start_time.strftime('%Y/%m/%d %H:%M') %> - <%= @event.end_time.strftime('%Y/%m/%d %H:%M') %>
        </div>
      </div>
  
      <div class="panel panel-default">
        <div class="panel-heading">
          <%= fa_icon 'map-marker' %>&nbsp;開催場所
        </div>
        <div class="panel-body">
          <%= @event.place %>&nbsp;
          <small>(<a href="https://maps.google.co.jp/maps?q=<%= @event.place %>" target="blank">Google Maps で検索</a>)</small>
        </div>
      </div>
  
      <div class="panel panel-default">
        <div class="panel-heading">
          <%= fa_icon 'edit' %>&nbsp;イベント内容
        </div>
        <div class="panel-body">
          <!--%= auto_link simple_format(h(@event.content)) %-->
          <%= markdown @event.content %>
        </div>
      </div>

      <% unless @event.event_attachments.blank? %>
        <ul class="list-group">
          <li class="list-group-item" style="background: #f5f5f5;"><%= fa_icon 'paperclip' %>&nbsp;添付ファイル</li>
          <% @event.event_attachments.each do |a| %>
            <%= link_to URI.decode(a.url.to_s.split('/').last), a.url.to_s, class: 'list-group-item' %>
          <% end %>
        </ul>
      <% end %>
  
      <!--Tweet Button-->
      <a href="https://twitter.com/share" class="twitter-share-button" data-size="large" data-hashtags="J305Project">Tweet</a>
      <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');twttr.widgets.load();</script>
    </div>
  
    <div class="col-md-4">
      <% if @event.created_by?(current_user) %>
        <%= link_to fa_icon('edit')+" イベントを編集する", edit_event_path(@event), class: 'btn btn-info btn-block' %>
        <%= link_to fa_icon('trash')+' イベントを削除する', event_path(@event), class: 'btn btn-danger btn-block', method: :delete, data: { confirm: '本当に削除しますか？' } %>
      <% end %>
  
      <% if @ticket %>
        <%= link_to fa_icon('close')+' 参加をキャンセルする', event_ticket_path(@event, @ticket), method: :delete, class: 'btn btn-warning btn-block' %>
      <% elsif logged_in? %>
        <button class="btn btn-primary btn-block" data-toggle="modal" data-target="#createTicket">
          <%= fa_icon('plus') %> 参加する
        </button>
  
        <!-- Modal Window -->
        <div class="modal fade" id="createTicket" tabindex="-1" role="dialog" aria-labelledby="dialogHeader" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="dialog-header">参加コメント <%= fa_icon 'comment' %></h4>
              </div>
  
              <%= form_for(@event.tickets.build, url: event_tickets_path(@event), remote: true) do |f| %>
                <div class="modal-body">
                  <%= f.text_field :comment, class: 'form-control' %>
                </div>
  
                <div class="modal-footer">
                  <button type="button" class="btn btn-default" data-dismiss="modal">キャンセル</button>
                  <%= f.button '送信', class: 'btn btn-primary', data: { disable_with: '送信中・・・' } %>
                </div>
              <% end %>
            </div>
          </div>
        </div><!-- Modal Window -->
      <% else %>
        <%= link_to 'ログインして参加する', root_path+'auth/twitter', class: 'btn btn-primary btn-block' %>
        <%= link_to 'Log in (test)', login_path, class: 'btn btn-primary btn-block' %>
      <% end %>
  
      <hr>
  
      <!-- Participants List -->
      <div class="panel panel-default">
        <div class="panel-heading">
          <%= fa_icon 'users' %>&nbsp;参加者
        </div>
        <div class="panel-body">
          <ul class="list-unstyled">
            <% @tickets.each do |ticket| %>
              <% if ticket.user %>
                <li>
                  <%= link_to url_for_twitter(ticket.user), target: '_blank' do %>
                    <%= image_tag ticket.user.image_url, width: 20, height: 20 %>
                    <%= "@#{ticket.user.nickname}" %>
                  <% end %>
                  <%= ticket.comment %>
                </li>
              <% else %>
                退会したユーザです
              <% end %>
            <% end %>
          </ul>
        </div>
      </div><!-- Participants List -->
  
    </div>
  </div>
</section>