project/config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'

  devise_for :admin_users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  get 'welcome/index'
  get 'welcome/check_login_and_redirect', as: :check_login_and_redirect
  get 'events/password', as: :page_authenticate
  post 'events/:id' => 'events#show'
  get 'mypage' => 'users#mypage', as: :mypage
  get '/auth/:provider/callback' => 'sessions#create'
  get '/login' => 'sessions#create', as: :login
  get '/logout' => 'sessions#destroy', as: :logout

  resource :user, only: :destroy do
    get 'retire'
  end

  resources :events do
    resources :tickets, only: [:new, :create, :destroy]
  end
  match '*path' => 'application#error404', via: :all

end

project/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title><%= content_for?(:title) ? "#{yield(:title)} | J305Project" : "J305Project"%></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<header id="header-global">
		<nav class="navbar navbar-fixed-top" role="navigation">
		  <div class="container">
        <div class="navbar-header" <% if false %>style="width: 100%; margin: 0;"<% end %>>
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <%= fa_icon('list lg') %>
          </button>
          <%= link_to 'J305Project', root_path, class: 'navbar-brand', title: 'トップページ' %>
        </div>

        <% unless logged_in? %>
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
              <li><%= link_to 'Log in (仮)', login_path %></li>
              <li>
                <%= link_to root_path+'auth/twitter', title: 'ログインするとイベントの主催・参加ができます' do %>
                  <%= fa_icon 'twitter' %> Log in with <b>Twitter</b>
                <% end %>
              </li>
            </ul>
          </div>
        <% end %>

      <% if logged_in? %>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to fa_icon('user') + ' マイページ', mypage_path, title: '主催・参加イベントを確認できます' %></li>
          	<li><%= link_to fa_icon('plus') + ' イベントを作る', new_event_path, title: '新しいイベントを主催' %></li>
            <li><%= link_to fa_icon('search') + ' イベント検索', events_path, title: 'イベントの検索' %></li>
          	<li>
              <div class="dropdown" id="userImage">
                <a href="" id="dropdownMenu1 " data-toggle="dropdown">
                  <%= image_tag current_user.image_url, class: 'img-rounded'%>
                </a>
                <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
                  <li class="dropdown-header"><%= " @#{current_user.nickname}" %></li>
                  <li><%= link_to fa_icon('plus')+'イベントを作る', new_event_path, title: '新しいイベントを主催' %></li>
                  <li><%= link_to  fa_icon('user')+' マイページ', mypage_path, title: '主催・参加イベントを確認できます' %></li>
                  <li><%= link_to  fa_icon('search')+' イベント検索', events_path, title: 'イベントの検索' %></li>
                  <li class="divider"></li>
                  <li><%= link_to  fa_icon('sign-out')+' ログアウト', logout_path, title: 'ログアウトします' %></li>
                  <li class="divider"></li>
                  <li><%= link_to  fa_icon('user-times')+' 退会', retire_user_path, title: '退会' %></li>
                </ul>
              </div>
          	</li>
          </ul>
        </div>
      <% end %>
		</nav>
	</header>

  <div id="wrap">
    <main>
      <%= yield %>
    </main>
  </div>

  <footer class="footer" id="footer-global">
    <div class="container">
      <ul class="list-inline center-block">
        <% if logged_in? %>
          <li><%= link_to fa_icon('user')+' Mypage', mypage_path, title: '主催・参加イベントを確認できます' %></li>
          <li><%= link_to fa_icon('plus')+' Create', new_event_path, title: '新しいイベントを主催' %></li>
        <% else %>
          <li><%= link_to fa_icon('twitter')+' Login with Twitter', root_path + 'auth/twitter', title: '主催・参加イベントを確認できます' %></li>
        <% end %>
        <li><%= link_to fa_icon('search')+' Search', events_path, title: 'イベントの検索' %></li>
      </ul>
    </div>
  </footer>
</body>
</html>