project/config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'

  devise_for :admin_users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  get 'welcome/index'
  get 'welcome/check_login_and_redirect', as: :check_login_and_redirect
  get 'events/password', as: :page_authenticate
  post 'events/:id' => 'events#show'
  get 'mypage' => 'users#mypage', as: :mypage
  get '/auth/:provider/callback' => 'sessions#create'
  get '/login' => 'sessions#create', as: :login
  get '/logout' => 'sessions#destroy', as: :logout

  resource :user, only: :destroy do
    get 'retire'
  end

  resources :events do
    resources :tickets, only: [:new, :create, :destroy]
  end
  match '*path' => 'application#error404', via: :all

end

project/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :store_location

  def index
    @events = Event.where('password is ?', nil).search({ start_time_gteq: Time.zone.now }).result
    @new_events = @events.order("created_at DESC").first(5)
    @popular_events = @events.joins(:tickets).select('*, events.id as id, count(*) as CNT').group(:id).order('CNT DESC').first(5)
  end

  def check_login_and_redirect
    if logged_in?
      redirect_to params.require(:path)
    else
      session[:return_to] = params.require(:path)
      redirect_to root_path + 'auth/twitter'
    end
  rescue
    redirect_to root_path
  end
end

project/app/helpers/welcome_helper.rb
module WelcomeHelper
end

project/app/views/welcome/index.html.erb
<section id="welcome">
  <div class="jumbotron">
    <div class="container">
      <h1>Welcome to J305 Project</h1>
      <!--p>This is a template for a simple marketing or informational website. It includes a large callout called a jumbotron and three supporting pieces of content. Use it as a starting point to create something more unique.</p-->
      <p>
        主催するイベントの登録、気になるイベントへの参加表明ができます。<br>
        Twitterのアカウントがあれば誰でもすぐに始めることができます。
      </p>
      <%= link_to root_path+'auth/twitter', class: 'btn btn-lg btn-twitter-login', title: 'ログインするとイベントの主催・参加ができます' do %>
        <%= fa_icon 'twitter' %> Log in with <b>Twitter</b> &raquo;
      <% end %>
    </div>
  </div>

  <nav class="container">
    <%= render partial: 'shared/flash_message' %>
    <ul class="row list-unstyled">
      <li class="col-md-4">
        <h4>Search for Events</h4>
        <p>まずはイベントを検索してみましょう。</p>
        <%= link_to events_path , class: 'btn btn-default' do %>
            <%= fa_icon 'search' %> イベントを検索
        <% end %>
      </li>
      <li class="col-md-4">
        <h4>Create New Events</h4>
        <p>主催するイベントを登録して参加者を募集しましょう。<br>(ログインする必要があります)</p>
        <%= link_to check_login_and_redirect_path(path: new_event_path), class: 'btn btn-default' do %>
            <%= fa_icon 'plus' %> イベントを作成
        <% end %>
      </li>
      <li class="col-md-4">
        <h4>Manage My Events</h4>
        <p>マイページでは主催・参加したイベントの管理が行えます。<br>(ログインする必要があります)</p>
        <%= link_to check_login_and_redirect_path(path: mypage_path), class: 'btn btn-default' do %>
            <%= fa_icon 'home' %> マイページ
        <% end %>
      </li>
    </ul><!-- row -->
  </nav>
</section>

<hr>
<section class="container">
  <div class="row">
    <div class="col-md-6">
      <%= render partial: 'shared/event_list', locals: {events: @new_events, heading: '新着イベント'} %>
    </div>
    <div class="col-md-6">
      <%= render partial: 'shared/event_list', locals: {events: @popular_events, heading: '人気イベント'} %>
    </div>
  </div>
</section>