project/config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'

  devise_for :admin_users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  get 'welcome/index'
  get 'welcome/check_login_and_redirect', as: :check_login_and_redirect
  get 'events/password', as: :page_authenticate
  post 'events/:id' => 'events#show'
  get 'mypage' => 'users#mypage', as: :mypage
  get '/auth/:provider/callback' => 'sessions#create'
  get '/login' => 'sessions#create', as: :login
  get '/logout' => 'sessions#destroy', as: :logout

  resource :user, only: :destroy do
    get 'retire'
  end

  resources :events do
    resources :tickets, only: [:new, :create, :destroy]
  end
  match '*path' => 'application#error404', via: :all

end

project/app/models/user.rb
class User < ActiveRecord::Base
	has_many :created_events, class_name: 'Event', foreign_key: :owner_id, dependent: :nullify
	has_many :tickets, dependent: :nullify
	has_many :participating_events, through: :tickets, source: :event

	def self.find_or_create_from_auth_hash(auth_hash)
		if auth_hash.nil? #テスト用
			# テスト用のデータ
			provider  = 'test'
			uid       = 'hogehoge'
			nickname  = 'hogehoge'
			image_url = '/icon1.png'
		else
			provider  = auth_hash[:provider]
			uid       = auth_hash[:uid]
			nickname  = auth_hash[:info][:nickname]
			image_url = auth_hash[:info][:image]
		end

		# 引数で渡した値を持つレコードが、
		# 存在すればそのオブジェクトを、
		# 存在しなければ値を設定してレコードを作成し、そのオブジェクトを返す
		User.find_or_create_by(provider: provider, uid: uid) do |user|
			user.nickname  = nickname
			user.image_url = image_url
		end
	end

	private

	def check_all_events_finished
		now = Time.zone.now
		if created_events.where(':now < end_time', now: now).exists?
			errors[:base] << '公開中の未終了イベントが存在します。'
		end

		if participating_events.where(':now < end_time', now: now).exists?
			errors[:base] << '未終了の参加イベントが存在します。'
		end
		errors.blank?
	end
end

project/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate

  def retire
  end

  def destroy
    if current_user.destroy
      reset_session
      redirect_to root_path, notice: '退会完了しました'
    else
      render retire
    end
  end

  def mypage
    @tickets = current_user.tickets.includes(:event)

    event_id_array = Array.new
    @tickets.each do |t|
      event_id_array << t.event_id
    end

    events_arel = Event.arel_table
    events_sel  = events_arel[:owner_id].eq(current_user.id)

    event_id_array.each do |event_id|
      events_sel = events_sel.or(events_arel[:id].eq(event_id))
    end

    hold_and_join_events = Event.where(events_sel).order(:start_time)

    @start_year = hold_and_join_events.first.start_time.year unless hold_and_join_events.first.nil?
    @end_year   = hold_and_join_events.last.start_time.year  unless hold_and_join_events.last.nil?

    @q = hold_and_join_events.page(params[:page]).per(PER).search(search_params)
    @events = @q.result(distinct: true)
  end
end

project/app/helpers/users_helper.rb
module UsersHelper
end

project/app/views/users/mypage.html.erb
<% provide(:title, "@#{current_user.nickname}") %>
<% provide(:page_title, "") %>
<% provide(:page_description, "@#{current_user.nickname}でログイン中") %>


<section class="container">
  <%= render partial: 'shared/flash_message' %>
  <header class="page-header">
    <h3>マイページ</h3>
    <p class="text-muted">主催・参加したイベントを管理できます</p>
    <p class="text-muted"><%= "@#{current_user.nickname}でログイン中" %></p>
    <small><%= link_to fa_icon('sign-out') + " ログアウト", logout_path %></small>
  </header>

  <%= render partial: 'shared/event_search_form', locals: {q: @q, start_year: @start_year, end_year: @end_year} %>
  <%= render partial: 'shared/event_search_result', locals: {events: @events} %>
</section>

project/app/views/users/retire.html.erb
<div class="pageheader">
  <h1>退会の確認</h1>
</div>
<% if current_user.errors.any? %>
  <div class="alert alert-danger">
    <ul>
      <% current_user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<p>退会時、ユーザに関連するすべてのデータが削除されます。</p>
<p>ただし、以下の場合は退会できません。</p>
<ul>
  <li>公開中の未終了イベントがある場合</li>
  <li>未終了の参加イベントがある場合</li>
</ul>
<hr>
<%= link_to '退会する', user_path, method: :delete, class: 'btn btn-danger' %>